services:
  accounts:
    image: "vikramb33/accounts:0.0.1"
    container_name: accounts_ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - banknetwork
networks:
  banknetwork:
    driver: "bridge"
